tumblr:
  blog_name: 'coupe-baguette'
  consumer_key: '(secret)'
  consumer_secret: '(secret)'
  oauth_token: '(secret)'
  oauth_token_secret: '(secret)'
excite:
  account_name: 'lapin418'
  id: '(secret)'
  pass: '(secret)'
  eid: '(secret)'
  latest_post_id: '(your post id)'
  oldest_post_id: '(your post id)'
